#ifndef TEXTURE_H
#define TEXTURE_H

#include "GL/glew.h"
#include <string>

struct TextureUnit{
    GLenum as_enum;
    GLint  as_int;
};

class Texture
{
public:
    bool initialize(std::string filePath, int texUnit);
    int getTextureUnit();
    void finish();
    void bind();
    void unbind();
private:
    GLuint m_handle;            // textureID as generated by OpenGL
    TextureUnit m_texture_unit; // which texture unit this should be bound to
    std::string m_texture_path; // path to texture file
    GLenum m_texture_type;
};

#endif // TEXTURE_H
